Add new version beta4
wlan0/direct-csi pull request #18
Opened 2022-03-06 18:02 UTC by sinhaashish

2022-03-07 06:02 UTC, Praveenrajmani commented
`pkg/converter` has to be fixed @sinhaashish can you compare with the other upgrade PRs and do the changes in `converter pkg`

2022-03-07 18:45 UTC, Praveenrajmani commented on pkg/apis/direct.csi.min.io/v1beta4/types.go
> +	MountPoints []string `json:"mountPoints,omitempty"`
```suggestion
	MountPoints []string `json:"mountpoints,omitempty"`
```

2022-03-07 18:49 UTC, Praveenrajmani reviewed
refer the other upgrade PRs to make sure we aren't missing anything

2022-03-07 18:49 UTC, Praveenrajmani commented on pkg/converter/volume_upgrade.go
> +func volumeUpgradeV1Beta3ToV1Beta4(unstructured *unstructured.Unstructured) error {
we should add a case in `upgradeVolumeObject` to call this function

2022-03-08 16:09 UTC, wlan0 commented on pkg/apis/direct.csi.min.io/v1beta4/types.go
> +	Mountpoints []string `json:"mountpoints,omitempty"`
Use []MountInfo instead of []string

2022-03-08 16:09 UTC, wlan0 commented on pkg/apis/direct.csi.min.io/v1beta4/types.go
> +	PciPath string `json:"pciPath,omitempty"`
PCI should be caps

2022-03-08 16:11 UTC, wlan0 commented on pkg/converter/drive_downgrade.go
> +	var v1beta4DirectCSIDrive directv1beta4.DirectCSIDrive
@Praveenrajmani Please verify

2022-03-16 03:32 UTC, sinhaashish commented on pkg/apis/direct.csi.min.io/v1beta4/types.go
> +	Mountpoints []string `json:"mountpoints,omitempty"`
Using MountPoints as slice of strings as using MountInfo would lead to circular dependency and we dont want all the info present in MountInfo

2022-03-16 20:44 UTC, Praveenrajmani requested changes
We should also set the other mounts in the drive object as discussed. LGTM otherwise. 

IMO, We can add `Hidden` later or in a separate PR

2022-03-16 20:44 UTC, Praveenrajmani commented on pkg/sys/types.go
> +	ty               string
What is this field? @sinhaashish

2022-03-17 04:09 UTC, Praveenrajmani commented on pkg/node/drive_event_handler_test.go
> +// This file is part of MinIO DirectPV
why is this file added? looks like an unrelated file

2022-03-18 15:49 UTC, closed without merging